name: power-ranger

on:
  repository_dispatch:
    types: [new-assignment-event]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout action repo
        uses: actions/checkout@v2
    
      - name: Checkout interns repo  
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo_name }}
          token: ${{secrets.GIT_HUB_TOKEN}}
          path: __source

      - name: Checkout test repo  
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.test_repo_name }}
          token: ${{secrets.GIT_HUB_TOKEN}}
          path: __test

      - name: configure node 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}  

      - name: Push new assignment 
        run: |
          node ranger.js ./__test/assignments.json
          
      - name: If new assignment has been created 
        id: verify_diff
        run: |
          cd __source
          git diff --quiet || echo "::set-output name=diff::true"    

      - name: Commit and push the next assignment name
        if: ${{ steps.verify_diff.outputs.diff }} == 'true'
        run: |
          cd __source
          git config user.name "JARVIS"
          git config user.email "<>"
          git add .
          git commit -m "New assignment created."
          git pull --rebase
          git push
