name: power-ranger

on:
  repository_dispatch:
    types: [new-assignment-event]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout action repo
        uses: actions/checkout@v2
    
      - name: Checkout interns repo  
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo_name }}
          token: ${{secrets.GIT_HUB_TOKEN}}
          path: __source

      - name: Checkout test repo  
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.test_repo_name }}
          token: ${{secrets.GIT_HUB_TOKEN}}
          path: __test

      - name: configure node 
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}  

      - name: Push new assignment 
        run: |
          node ranger.js ./__test/assignments.json
          
      - name: If new assignment has been created 
        id: verify_diff
        run: |
          cd __source
          git add .
          git diff --cached --quiet || echo "::set-output name=diff::true"
          echo "LOCAL_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "REMOTE_COMMIT=${{ github.event.client_payload.body.commit.id }}" >> $GITHUB_ENV
          echo "DIRTY=$(git diff --cached)" >> $GITHUB_ENV

      - name:
        id: if_redundant_commit
        if: ${{ env.REMOTE_COMMIT != env.LOCAL_COMMIT }}
        run: |
          exit 1

      - name: Commit and push the next assignment name
        if: ${{ env.DIRTY != '' }}
        run: |
          cd __source
          git config user.name "JARVIS"
          git config user.email "<>"
          git add .
          git commit -m "New assignment created."
          git pull --rebase
          git push
